/*************/
/* IMPORT(S) */
/*************/
import java_cup.runtime.*;
import ast.*;
import java.io.PrintWriter;


parser code 
{:
	public Lexer lexer;
	public PrintWriter writer;

	public Parser(Lexer lexer, PrintWriter writer)
	{
		super(lexer);
		this.lexer = lexer;
		this.writer = writer;
	}
	public void report_error(String message, Object info)
	{
		
	}
	public void syntax_error(Symbol curr_token){
		int err_line = curr_token.left +1;
		writer.print("ERROR(" + err_line + ")");
		writer.close();
		System.exit(0);
	}
:}

/************************/
/* CUSTOMIZE CUP PARSER */
/************************/
scan with
{:
	Symbol s;
	s = lexer.next_token();
	//System.out.print(s.sym);
	//Block for debug - delete later -----------------------------------------
	System.out.print("[");
	System.out.print(lexer.getLine());
	System.out.print(":");
	System.out.print(lexer.getTokenStartPosition());
	System.out.print("] ");
	System.out.print(TokenNames.terminalNames[s.sym]);
	if (s.value != null)
	{
		System.out.print("( ");
		System.out.print(s.value);
		System.out.print(" )");
	}
	System.out.print("\n");
	//-------------------------------------------------------------------------
	return s; 
:};

/*************/
/* TERMINALS */
/*************/
terminal TYPE_INT;
terminal TYPE_STRING;
terminal TYPE_VOID;
terminal IF;
terminal EQ;
terminal DOT;
terminal PLUS;
terminal MINUS;
terminal TIMES;
terminal WHILE;
terminal DIVIDE;
terminal LPAREN;
terminal RPAREN;
terminal LBRACK;
terminal RBRACK;
terminal LBRACE;
terminal RBRACE;
terminal SEMICOLON;
terminal CLASS;
terminal COMMA;
terminal ASSIGN;
terminal ARRAY;
terminal NIL;
terminal LT;
terminal GT;
terminal NEW;
terminal RETURN;
terminal ELSE;
terminal EXTENDS;
/*************/
/* TERMINALS */
/*************/
terminal Integer INT;
terminal String STRING;
terminal String ID;

/*****************/
/* NON TERMINALS */
/*****************/
non terminal AstExp exp;
non terminal AstVar var;
non terminal AstStmt stmt;
non terminal AstStmtList stmtList;
non terminal AstDec dec;
non terminal AstParamList paramList;
non terminal AstType type;
non terminal AstCField cField;
non terminal AstCFieldList cFieldList;
non terminal AstCallExp callExp;
non terminal AstExpList expList;
non terminal AstNewExp newExp;
non terminal AstStmtElse elseStmt;
non terminal AstProgram program;
non terminal AstVarDec varDec;
non terminal AstFuncDec funcDec;
/***********************/
/* OPERATOR PRECEDENCE */
/***********************/

/* Level 1: Assignment (Lowest) */
precedence nonassoc ASSIGN, ELSE;
/* Level 2: Equality */
precedence left EQ;

/* Level 3: Relational (Grouping LT and GT together) */
precedence left LT, GT;

/* Level 4: Additive */
precedence left PLUS, MINUS;

/* Level 5: Multiplicative */
precedence left TIMES, DIVIDE;

/* Level 6: Array Indexing */
precedence nonassoc LBRACK;

/* Level 7: Function Call */
precedence nonassoc LPAREN;

/* Level 8: Field Access (Highest) */
precedence left DOT;
/************************/
/* START WITH: program */
/************************/
start with program;

/********************/
/* DERIVATION RULES */
/********************/

program		::=		dec: d 					{: RESULT = new AstProgram(d,null, dleft);    :}
					| dec: d program: p		{: RESULT = new AstProgram(d, p, dleft);    :}
					;

stmtList	::=		stmt:s	stmtList:l		{: RESULT = new AstStmtList(s,l, sleft);    :}
					| stmt:s				{: RESULT = new AstStmtList(s,null, sleft); :}
					;

dec			::=		varDec: v			{: RESULT = v; :}
					| funcDec: f        {: RESULT = f; :}
					| CLASS ID: i LBRACE cFieldList: l RBRACE {: RESULT = new AstClassDec(i, null, l, ileft); :}
					| CLASS ID: i EXTENDS ID: parent LBRACE cFieldList: l RBRACE {: RESULT = new AstClassDec(i, parent, l, ileft); :}

					| ARRAY ID EQ type: t LBRACK RBRACK SEMICOLON {: RESULT = new AstArrayTypedef(t, tleft); :}
					;
varDec		::= 	type: t ID: i SEMICOLON								{: RESULT = new AstVarDec(t, i, null,tleft); :}
					| type: t ID: i ASSIGN exp: e  SEMICOLON 			{: RESULT = new AstVarDec(t, i, e, tleft); :}
					| type: t ID: i ASSIGN newExp: n SEMICOLON 			{: RESULT = new AstVarDec(t, i, n, tleft); :}
					;
funcDec     ::=     type: t ID: i LPAREN RPAREN LBRACE stmtList: s RBRACE					{: RESULT = new AstFuncDec(t, i, null, s, tleft); :}
                    | type: t ID: i LPAREN paramList: p RPAREN LBRACE stmtList: s RBRACE 	{: RESULT = new AstFuncDec(t, i, p, s, tleft); :}
                    ;
paramList	::=		type: t ID: i						{: RESULT = new AstParamList(t, i, null, tleft); :}
					| type: t ID: i COMMA paramList: p	{: RESULT = new AstParamList(t, i, p, tleft); :}
					;


cFieldList	::= 	cField: c 					{: RESULT = new AstCFieldList(c, null, cleft); :}
					| cField: c cFieldList: l	{: RESULT = new AstCFieldList(c, l, cleft); :}
					;
cField		::=		varDec: v 			{: RESULT = new AstCField(v, vleft); :}
					| funcDec: f 		{: RESULT = new AstCField(f, fleft); :}
					;


type 		::= 	TYPE_INT:t    	{: RESULT = new AstType("int", tleft); :}
					| TYPE_STRING:t {: RESULT = new AstType("string", tleft); :}
					| TYPE_VOID:t   {: RESULT = new AstType("void", tleft); :}
					| ID:i          {: RESULT = new AstType(i, ileft); :}
					;

exp			::=		var:v								{: RESULT = new AstExpVar(v, vleft);           :}
					| LPAREN exp: e RPAREN				{: RESULT = e;                                 :}
					| exp:e1 PLUS   exp:e2				{: RESULT = new AstExpBinop(e1, e2, 0, e1left);:}
					| exp:e1 MINUS  exp:e2				{: RESULT = new AstExpBinop(e1, e2, 1, e1left);:}
					| exp:e1 TIMES  exp:e2				{: RESULT = new AstExpBinop(e1, e2, 2, e1left);:}
					| exp:e1 DIVIDE exp:e2				{: RESULT = new AstExpBinop(e1, e2, 3, e1left);:}
					| exp:e1 LT 	exp:e2				{: RESULT = new AstExpBinop(e1, e2, 4, e1left);:}
					| exp:e1 GT 	exp:e2				{: RESULT = new AstExpBinop(e1, e2, 5, e1left);:}
					| exp:e1 EQ 	exp:e2				{: RESULT = new AstExpBinop(e1, e2, 6, e1left);:}
					| callExp: c						{: RESULT = c;:}
					| MINUS INT: i						{: RESULT = new AstExpInt(-i, ileft);:}
					| INT: i							{: RESULT = new AstExpInt(i, ileft);:}
					| NIL: n							{: RESULT = new AstExpNil(nleft);:}
					| STRING: s							{: RESULT = new AstExpString(s, sleft);:}
					;

callExp		::=		ID: i LPAREN RPAREN					        {: RESULT = new AstCallExp(null, i, null, ileft);:}
                    | ID: i LPAREN expList: l RPAREN	        {: RESULT = new AstCallExp(null, i, l, ileft);:}
                    | var:v DOT ID: i LPAREN RPAREN		        {: RESULT = new AstCallExp(v, i, null, ileft);:}
					| var:v DOT ID: i LPAREN expList: l RPAREN	{: RESULT = new AstCallExp(v, i, l, ileft);:}
					;

expList		::=		exp: e 								{: RESULT = new AstExpList(e, null, eleft);:}
					| exp: e COMMA expList: l			{: RESULT = new AstExpList(e, l, eleft);:}
					;

newExp		::= 	NEW type: t							{: RESULT = new AstNewExp(t, null, tleft);:}
					| NEW type: t LBRACK exp: e RBRACK	{: RESULT = new AstNewExp(t, e, tleft);:}
					;

var			::=		ID:name								{: RESULT = new AstVarSimple(name, nameleft);:}
					| var:v DOT ID:fieldName			{: RESULT = new AstVarField(v, fieldName, vleft); :}
					| var:v LBRACK exp:e RBRACK			{: RESULT = new AstVarSubscript(v, e, vleft);     :}
					;
					
stmt		::=		varDec: v															{: RESULT = new AstStmtDec(v, vleft); :}
					| var:v ASSIGN exp:e SEMICOLON										{: RESULT = new AstStmtAssign(v, e, vleft); :}
					| var:v ASSIGN newExp:n SEMICOLON									{: RESULT = new AstStmtAssign(v, n, vleft); :}
					| RETURN: r SEMICOLON												{: RESULT = new AstStmtReturn(null, rleft); :}
					| RETURN exp: e SEMICOLON											{: RESULT = new AstStmtReturn(e, eleft); :}
					| IF    LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE					{: RESULT = new AstStmtIf(cond, body, null, condleft); :}
					| IF    LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE elseStmt: e		{: RESULT = new AstStmtIf(cond, body, e, condleft); :}
					| WHILE LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE			{: RESULT = new AstStmtWhile(cond, body, condleft); :}
					| callExp: c SEMICOLON												{: RESULT = new AstStmtCall(c, cleft); :}
					;
elseStmt	::=		ELSE LBRACE stmtList: s RBRACE				{: RESULT = new AstStmtElse(s,sleft); :};